# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5549db63c830dc48fd7b005121ecd4fa2129eb389f131e0e6788ab9a74b62c75364195ad7ae48168f80daf28d64f403598f6e38ce328a23dc23dfe8e25380887

test:
  secret_key_base: 18b56547e2425d55850cf1b60f00b86433525d89f31bb3f6327595c7be8c95a7989319bbdcaf18a847a348a67704f6bb3fe6a4dc2985a2098cd97bdd488c6463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
